### ISSUE TITLE
2020plus.py not found

### ISSUE THREAD

**Issue by complexgenome** [KarchinLab/2020plus#28]
Dear Developers,
I'm keen to use 20/20+ for drivers analysis. I've multiple myeloma as cancer type.

I follow steps as provided on instructions https://2020plus.readthedocs.io/en/latest/installation.html

The conda environment is created, I was able to install the additional R/python libraries. However, I cannot find 2020plus.py anywhere in the folder. I followed steps to change the PATH variable but no luck.

Please let me know how to proceed.

**Comment by ctokheim** [comment]
Did you fill out the following line to the actual location where you downloaded the 2020plus folder to? For example, if I had downloaded the 2020plus folder to /Users/ctokheim/2020plus, then one should change the path in the install documentation from

```{bash}
export PATH=$PATH:/path/to/2020plus
```

to this

```{bash}
export PATH=$PATH:/Users/ctokheim/2020plus
```

Also note that if you enter the above into your .bashrc file then you will need to restart your terminal so that the update to the .bashrc is loaded, or alternatively force the newly updated .bashrc to be reloaded by using `source ~/.bashrc`

**Comment by complexgenome** [comment]
@ctokheim Thanks for your response.
Sorry I thought that conda installation will pull the script. 

I downloaded the software folder and put it in the folder.

`which 2020plus.py `

`/data1/users/sanjeev/drivers/2020/2020plus-1.2.3/`

When I run I get error for something:

`python 2020plus.py `

```
Failed to import the site module
Traceback (most recent call last):
  File "/data1/software/miniconda/envs/2020plus/lib/python3.6/site.py", line 545, in <module>
    main()
  File "/data1/software/miniconda/envs/2020plus/lib/python3.6/site.py", line 531, in main
    known_paths = addusersitepackages(known_paths)
  File "/data1/software/miniconda/envs/2020plus/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/data1/software/miniconda/envs/2020plus/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/data1/software/miniconda/envs/2020plus/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/data1/software/miniconda/envs/2020plus/lib/python3.6/sysconfig.py", line 609, in get_config_var
    return get_config_vars().get(name)
  File "/data1/software/miniconda/envs/2020plus/lib/python3.6/sysconfig.py", line 558, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/data1/software/miniconda/envs/2020plus/lib/python3.6/sysconfig.py", line 429, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_linux_gnu'

```

How do I resolve this?
The error is primarily associated with the dependencies shipped in the requirements.yalm file.

I installed
conda install -c anaconda gcc_linux-64

It doesn't solve.

**Comment by complexgenome** [comment]
Never mind, I solved it as:

cp /data1/software/miniconda/envs/2020plus/lib/python3.6/_sysconfigdata_x86_64_conda_cos6_linux_gnu.py /data1/software/miniconda/envs/2020plus/lib/python3.6/_sysconfigdata_x86_64_conda_cos7_linux_gnu.py
